# In-game constants
BUY_BACK_COST = 4500
LOADOUT_COST = 10000

# Time constants (in seconds after game start)
GAME_START_CUT_SCENE = 22

CIRCLE_1_LENGTH = 220
CIRCLE_1_END = GAME_START_CUT_SCENE + CIRCLE_1_LENGTH
CIRCLE_1_MOVING = 270

CIRCLE_2_LENGTH = 90
CIRCLE_2_END = CIRCLE_1_END + CIRCLE_1_MOVING + CIRCLE_2_LENGTH
CIRCLE_2_MOVING = 220

CIRCLE_3_LENGTH = 75
CIRCLE_3_END = CIRCLE_2_END + CIRCLE_2_MOVING + CIRCLE_3_LENGTH
CIRCLE_3_MOVING = 170

CIRCLE_4_LENGTH = 60
CIRCLE_4_END = CIRCLE_3_END + CIRCLE_3_MOVING + CIRCLE_4_LENGTH
CIRCLE_4_MOVING = 110

CIRCLE_5_LENGTH = 60
CIRCLE_5_END = CIRCLE_4_END + CIRCLE_4_MOVING + CIRCLE_5_LENGTH
CIRCLE_5_MOVING = 70

CIRCLE_6_LENGTH = 45
CIRCLE_6_END = CIRCLE_5_END + CIRCLE_5_MOVING + CIRCLE_6_LENGTH
CIRCLE_6_MOVING = 50

CIRCLE_7_LENGTH = 30
CIRCLE_7_END = CIRCLE_6_END + CIRCLE_6_MOVING + CIRCLE_7_LENGTH
CIRCLE_7_MOVING = 50

FINAL_CIRCLE_LENGTH = 100

LOADOUT_DROP_1 = CIRCLE_1_END + CIRCLE_1_MOVING - 14
LOADOUT_DROP_2 = CIRCLE_4_END + CIRCLE_4_MOVING + 16
GULAG_CLOSED = CIRCLE_4_END + CIRCLE_4_MOVING